names=['john','lily','kate','esther','mordecai','Victor','phoebe','kiki','candy','mugambi','phinehas','aquinas']
print(names[-9:])
print("Here are the first five names in a list.")
for name in names[:5]:
    print(name.title())
print("The first three items in the list are:")  
print(names[:3])
print("The names from the middle of the list are:")
print(names[-6:])
print("The last three items in the list are:\n")
print(names[-3:])
print("The first five names are:")
print(names[:5])
print("The last four names are:")
print(names[-4:])